# Generated by Django 4.1.5 on 2023-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(max_length=5000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='', max_length=600),
        ),
    ]
